### ISSUE TITLE
Jsonable fields are getting all logged right now, even when there is not a single change

### ISSUE THREAD

**Issue by TimFoerster** [samuelpatro/revisions-plugin#33]
They have also null values instead of empty arrays. Don't know if that is Ocms v3 related.

![image](https://user-images.githubusercontent.com/7849550/174847916-aaf1c2e7-f14b-41c1-9a48-a09bb53499ee.png)

**Comment by TimFoerster** [comment]
All entries are also stored twice?

**Comment by Samuell1** [comment]
@TimFoerster Hey, you need to only include trait from this plugin, if you add both traits it will fire 2 times.

**Comment by TimFoerster** [comment]
This is already the case

```php
use Samuell\Revisions\Traits\Revisions;

class Company extends Model
{
    use Revisions;

    protected $revisionable = [
        'section',
        'name',
        'address',
        'type',
        'station_id',
        'content',
        'contacts',
        'divisions',
        'persons'
    ];
    ...    
```

**Comment by Samuell1** [comment]
@TimFoerster if you remove that bindEvent it works correctly?

**Comment by skacco** [comment]
I have the same problem.
You need to comment this part on your plugin inside revisions/traits/Revisions.php

           /* $model->bindEvent('model.afterUpdate', function () use ($model) {
                $model->revisionableAfterUpdate();
            });

            $model->bindEvent('model.afterDelete', function () use ($model) {
                $model->revisionableAfterDelete();
            });*/

**Comment by Samuell1** [comment]
@skacco @TimFoerster Hey, if you can pull master changes and try it out if it works correctly, Thanks!
